/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Create a `.undo` directory under `workdir`. */
export declare function init(workdir: string): void
/** Mark a checkpoint. Returns its id. */
export declare function checkpoint(workdir: string, label: string): string
/**
 * Capture a path (recursively, if a directory) before the agent changes it.
 * Returns a newline-joined description of every effect recorded.
 */
export declare function track(workdir: string, path: string): string
/** Record a network mutation with an optional compensating request. */
export declare function recordHttp(workdir: string, method: string, url: string, compMethod?: string | undefined | null, compUrl?: string | undefined | null, compBody?: string | undefined | null): void
/** JSON `{ checkpoint, effects }` for what's changed since the last checkpoint. */
export declare function statusJson(workdir: string): string
/** JSON array of every journal row, oldest first. */
export declare function logJson(workdir: string): string
/**
 * Rewind everything since `target` (or the latest checkpoint). Returns a JSON
 * `{ checkpoint, reverted, skipped, failed }` report. If `failed` is non-empty
 * the journal was left intact and the rollback can be retried.
 */
export declare function rollback(workdir: string, target?: string | undefined | null): string
/** Undo the last rollback. Returns a JSON `{ restored, failed }` report. */
export declare function redo(workdir: string): string
/**
 * Selective undo: reverse just one file. Returns a description, or null if the
 * path wasn't tracked.
 */
export declare function revert(workdir: string, path: string): string | null
/**
 * JSON array of `{ path, status, added, removed, hunk }` — a PR-style diff of
 * everything changed since the last checkpoint.
 */
export declare function diffJson(workdir: string): string
